# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: graphqls-to-asciidoc

before:
  hooks:
    - go mod tidy
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      # No windows, because syslog is not on windows.
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
      - v2
      - v3
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if and (eq .Arch "amd64") .Amd64 }}_{{ .Amd64 }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Enhancements'
      regexp: "^.*enhance[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

# Homebrew tap configuration
brews:
  - name: graphqls-to-asciidoc
    repository:
      owner: bovinemagnet
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: "https://github.com/bovinemagnet/graphqls-to-asciidoc"
    description: "Convert GraphQL schema files to comprehensive AsciiDoc documentation"
    license: "MIT"
    test: |
      system "#{bin}/graphqls-to-asciidoc -version"
    install: |
      bin.install "graphqls-to-asciidoc"

release:
  github:
    owner: bovinemagnet
    name: graphqls-to-asciidoc
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

#snapshot:
#  name_template: "{{ incpatch .Version }}-next"
