repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: local
    hooks:
      - id: go-fmt
        name: go-fmt
        entry: make fmt-check
        language: system
        types: [go]
        pass_filenames: false
      
      - id: go-vet
        name: go-vet
        entry: make vet
        language: system
        types: [go]
        pass_filenames: false
      
      - id: go-lint
        name: go-lint
        entry: make lint
        language: system
        types: [go]
        pass_filenames: false
      
      - id: go-test
        name: go-test
        entry: make test
        language: system
        types: [go]
        pass_filenames: false